### ISSUE TITLE
Header: No  top padding for the search field.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Pump-Engineering#103]
![image](https://cloud.githubusercontent.com/assets/11186313/16720561/37aa90b2-476a-11e6-9282-d51011dc8877.png)

**Comment by charmander-titan** [comment]
backend menu overlaps the search bar. Please log off from back end or use incognito window.

**Comment by ricatitan** [comment]
It exceeds from 400px and below
![image](https://cloud.githubusercontent.com/assets/18568310/17049123/d0f07456-501d-11e6-903d-b4186e10a0ab.png)
