### ISSUE TITLE
Home - recent news: Images should have uniform height by default. Post title and description should be aligned.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Pump-Engineering#104]
![image](https://cloud.githubusercontent.com/assets/11186313/16720710/a95dae28-476b-11e6-832f-d963696a8889.png)

**Comment by charmander-titan** [comment]
rightmost image has lesser height dimension:211px; that's why the post title and description were not aligned. 
-Fixed the post title and description alignment, but the image still remains small. Need to replace the image with a bigger dimension.
