### ISSUE TITLE
Homepage- Recent News: Incorrect margin height for image when not in hover. 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Pump-Engineering#11]
![image](https://cloud.githubusercontent.com/assets/18568310/16138883/8c17a576-3474-11e6-8076-4bfe1467f89d.png)

![image](https://cloud.githubusercontent.com/assets/18568310/16138877/8202fd10-3474-11e6-9dab-0e918b65ae7b.png)

**Comment by ricatitan** [comment]
Same error

![image](https://cloud.githubusercontent.com/assets/18568310/16793453/bb95a020-4903-11e6-8e99-517bc3ddd8b4.png)

**Comment by charmander-titan** [comment]
original image dimension is too small: height: 211px;
