### ISSUE TITLE
Parts Listing: Incorrect font size for post title and contents

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Pump-Engineering#128]
![image](https://cloud.githubusercontent.com/assets/18568310/16797640/0772e13a-491b-11e6-947c-7ef7c1a53192.png)

**Comment by charmander-titan** [comment]
For consistency on pages; services and news:
Page Title: 18px;
Page Content: 12px;
Image height: 158px;

**Comment by ricatitan** [comment]
Page content is 16px as per design even in services and news
