### ISSUE TITLE
Pumps Listing: Are sub-categories should also be display? please confirm. It is not found in the design

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Pump-Engineering#90]
![image](https://cloud.githubusercontent.com/assets/18568310/16215721/0a57ac4a-3797-11e6-900b-0770c3e3c45d.png)

**Comment by charmander-titan** [comment]
not found in the design. Sub categories are already removed in product listing

**Comment by roseliesromeo** [comment]
Should be shown under its parent category. If there are category pages, subcategories should also be styled similarly as the parent categories.
