### ISSUE TITLE
Pumps Page: Incorrect default image

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Pump-Engineering#92]
![image](https://cloud.githubusercontent.com/assets/18568310/16215901/c72c893e-3798-11e6-95f5-c7ddb7b720be.png)

**Comment by roseliesromeo** [comment]
Not fixed in the listing page and single page.  
![image](https://cloud.githubusercontent.com/assets/11186313/16720752/faebd328-476b-11e6-91d7-8d56715d096b.png)
![image](https://cloud.githubusercontent.com/assets/11186313/16720774/1256d238-476c-11e6-8641-0b732b210717.png)
