### ISSUE TITLE
Header Menus: Incorrect design for dropdown sub-menus.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Pump-Engineering#95]
![image](https://cloud.githubusercontent.com/assets/18568310/16216171/2899f358-379b-11e6-8c57-eef6ca2ad6c0.png)

**Comment by roseliesromeo** [comment]
Lacking arrows 
![image](https://cloud.githubusercontent.com/assets/11186313/16719541/2236dabc-475e-11e6-8e76-dde47c463f1c.png)
