### ISSUE TITLE
Homepage Menu: Add arrow icon if there are sub menus

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Pump-Engineering#98]
![image](https://cloud.githubusercontent.com/assets/18568310/16216658/2ea9d37c-379f-11e6-90a9-34ac17bf6d41.png)

**Comment by roseliesromeo** [comment]
Not applied
![image](https://cloud.githubusercontent.com/assets/11186313/16720594/7a1a55fe-476a-11e6-9134-d9cbc5e843fb.png)
